"""Prominent pilot e-books with their exact verified source pages.

Every entry MUST point at a real, exact source page for the item it names.
Never point a book title at a different document's file.
"""

from __future__ import annotations

PROMINENT_EBOOKS: list[dict] = [
    {
        "id": "corpus_book_artificial_intelligence_a_new_synthesis_1998",
        "title": "Artificial Intelligence: A New Synthesis",
        "author": "Nils J. Nilsson",
        "year": "1998",
        "isPearson": False,
        "primaryColor": "#2563eb",
        "accentColor": "#93c5fd",
        "domain": "Artificial Intelligence & Machine Learning",
        "pdfUrl": "https://archive.org/details/artificialintell0000nils",
        "resolveUrl": "https://archive.org/details/artificialintell0000nils",
        "desc": "Foundational text on agent architectures, state-space search, logic, probabilistic reasoning, and neural networks.",
        "isbn": "9781558604674",
        "page_count": 533,
        "toc": [
            {"title": "Chapter 1: Reactive Agents", "page": 1},
            {"title": "Chapter 2: Search in State Spaces", "page": 25},
            {"title": "Chapter 3: Planning & Logic", "page": 89},
        ],
    },
    {
        "id": "paper_attention_is_all_you_need_2017",
        "title": "Attention Is All You Need",
        "author": "Vaswani et al.",
        "year": "2017",
        "isPearson": False,
        "primaryColor": "#7c3aed",
        "accentColor": "#c4b5fd",
        "domain": "Artificial Intelligence & Machine Learning",
        "pdfUrl": "https://huggingface.co/datasets/Prataykarali/Library_books/blob/main/papers/Vaswani2017_Attention_Is_All_You_Need.pdf",
        "resolveUrl": "https://huggingface.co/datasets/Prataykarali/Library_books/resolve/main/papers/Vaswani2017_Attention_Is_All_You_Need.pdf",
        "desc": "Introduces multi-head self-attention mechanisms, eliminating recurrence and convolution in sequence models.",
        "isbn": "ArXiv-1706.03762",
        "page_count": 15,
        "toc": [
            {"title": "1. Introduction & Background", "page": 1},
            {"title": "2. Multi-Head Attention", "page": 5},
        ],
    },
    {
        "id": "book_math_for_machine_learning_2020",
        "title": "Mathematics for Machine Learning",
        "author": "Marc Peter Deisenroth et al.",
        "year": "2020",
        "isPearson": False,
        "primaryColor": "#059669",
        "accentColor": "#6ee7b7",
        "domain": "Signal Processing & Mathematics",
        "pdfUrl": "https://huggingface.co/datasets/Prataykarali/Library_books/blob/main/textbooks/Deisenroth_Math_For_ML.pdf",
        "resolveUrl": "https://huggingface.co/datasets/Prataykarali/Library_books/resolve/main/textbooks/Deisenroth_Math_For_ML.pdf",
        "desc": "Linear algebra, analytic geometry, matrix decompositions, vector calculus, and optimization for ML models.",
        "isbn": "9781108455145",
        "page_count": 398,
        "toc": [
            {"title": "Part I: Mathematical Foundations", "page": 1},
            {"title": "Part II: Central Machine Learning Problems", "page": 200},
        ],
    },
    {
        "id": "paper_goodfellow_2014_gan",
        "title": "Generative Adversarial Nets",
        "author": "Ian Goodfellow, Jean Pouget-Abadie, Mehdi Mirza, Bing Xu, David Warde-Farley, Sherjil Ozair, Aaron Courville",
        "year": "2014",
        "isPearson": False,
        "isPaper": True,
        "primaryColor": "#0891b2",
        "accentColor": "#67e8f9",
        "domain": "Artificial Intelligence & Machine Learning",
        "pdfUrl": "https://huggingface.co/datasets/Prataykarali/Library_books/blob/main/papers/Goodfellow2014_GAN.pdf",
        "resolveUrl": "https://huggingface.co/datasets/Prataykarali/Library_books/resolve/main/papers/Goodfellow2014_GAN.pdf",
        "desc": "Introduces generative adversarial networks: paired generator/discriminator minimax training for synthetic data.",
        "isbn": "ArXiv-1406.2661",
        "page_count": 30,
        "toc": [
            {"title": "1. Introduction", "page": 1},
            {"title": "2. Related Work", "page": 2},
            {"title": "3. GANs", "page": 4},
        ],
    },
    {
        "id": "book_speech_and_language_processing_jurafsky",
        "title": "Speech and Language Processing",
        "author": "Dan Jurafsky & James H. Martin",
        "year": "2023",
        "isPearson": False,
        "primaryColor": "#dc2626",
        "accentColor": "#fca5a5",
        "domain": "Artificial Intelligence & Machine Learning",
        "pdfUrl": "https://web.stanford.edu/~jurafsky/slp3/",
        "resolveUrl": "https://web.stanford.edu/~jurafsky/slp3/",
        "desc": "Classic NLP and computational linguistics reference covering n-grams, transformers, machine translation, and dialogue systems.",
        "isbn": "9780131873216",
        "page_count": 945,
        "toc": [{"title": "Chapter 10: Transformers and Pretrained Models", "page": 210}],
    },
    {
        "id": "ostep_three_easy_pieces",
        "title": "Operating Systems: Three Easy Pieces (OSTEP)",
        "author": "Remzi H. Arpaci-Dusseau, Andrea C. Arpaci-Dusseau",
        "year": "2018",
        "isPearson": False,
        "primaryColor": "#d97706",
        "accentColor": "#fde68a",
        "domain": "Operating Systems & Architecture",
        "pdfUrl": "/pdfs/ostep_three_easy_pieces/00_Dialogue.pdf",
        "resolveUrl": "/pdfs/ostep_three_easy_pieces/00_Dialogue.pdf",
        "desc": "Foundational operating systems architecture text covering CPU virtualization, memory paging, concurrency, and log-structured storage. Opens at the first chapter of the locally indexed chapter set.",
        "isbn": "9781985086593",
        "page_count": 0,
        "toc": [
            {"title": "Dialogue on Virtualization", "page": 1},
            {"title": "CPU Virtualization", "page": 1},
            {"title": "Paging", "page": 1},
        ],
    },
]
