"""Authoritative booth demo-query book rows (CSV is an export of this table)."""
from __future__ import annotations

from typing import Any

# page_number is the physical PDF page to open for that topic.
DEMO_BOOK_ROWS: list[dict[str, Any]] = [
    {
        "query_key": "lora",
        "book_id": "hu2021_lora",
        "doc_id": "papers/Hu2021_LoRA.pdf",
        "book_title": "LoRA: Low-Rank Adaptation of Large Language Models",
        "authors": "Edward J. Hu et al.",
        "total_copies": 3,
        "available_copies": 2,
        "availability": "Available",
        "is_reference": False,
        "shelf_location": "AIML-PEFT-01",
        "page_number": 4,
        "topic": "Low-Rank Adaptation",
        "summary": "Freezes W0 and injects trainable low-rank matrices BA into each Transformer layer.",
    },
    {
        "query_key": "lora",
        "book_id": "peft_survey",
        "doc_id": "papers/Hu2021_LoRA.pdf",
        "book_title": "Parameter-Efficient Fine-Tuning Survey (library copy)",
        "authors": "Library PEFT Collection",
        "total_copies": 2,
        "available_copies": 1,
        "availability": "Available",
        "is_reference": True,
        "shelf_location": "AIML-PEFT-REF",
        "page_number": 1,
        "topic": "PEFT",
        "summary": "Reference survey of parameter-efficient fine-tuning methods including LoRA.",
    },
    {
        "query_key": "rag",
        "book_id": "lewis2020_rag",
        "doc_id": "papers/Lewis2020_RAG.pdf",
        "book_title": "Retrieval-Augmented Generation for Knowledge-Intensive NLP",
        "authors": "Patrick Lewis et al.",
        "total_copies": 4,
        "available_copies": 3,
        "availability": "Available",
        "is_reference": False,
        "shelf_location": "AIML-RAG-01",
        "page_number": 3,
        "topic": "RAG-Sequence and RAG-Token",
        "summary": "Combines a parametric seq2seq generator with a non-parametric dense Wikipedia index.",
    },
    {
        "query_key": "rag",
        "book_id": "graphrag_ms",
        "doc_id": "papers/Edge2024_GraphRAG.pdf",
        "book_title": "GraphRAG / hybrid retrieval notes (library binder)",
        "authors": "Microsoft Research / library notes",
        "total_copies": 2,
        "available_copies": 2,
        "availability": "Available in library",
        "is_reference": True,
        "shelf_location": "AIML-RAG-REF",
        "page_number": 1,
        "topic": "GraphRAG",
        "summary": "Reference binder on graph-structured retrieval and community summaries.",
    },
    {
        "query_key": "bert",
        "book_id": "devlin2018_bert",
        "doc_id": "papers/Devlin2018_BERT.pdf",
        "book_title": "BERT: Pre-training of Deep Bidirectional Transformers",
        "authors": "Jacob Devlin et al.",
        "total_copies": 5,
        "available_copies": 4,
        "availability": "Available",
        "is_reference": False,
        "shelf_location": "AIML-NLP-01",
        "page_number": 3,
        "topic": "Masked Language Modeling",
        "summary": "Bidirectional Transformer pre-training with MLM and next-sentence prediction.",
    },
    {
        "query_key": "bert",
        "book_id": "vaswani2017_attention",
        "doc_id": "papers/Vaswani2017_Attention_Is_All_You_Need.pdf",
        "book_title": "Attention Is All You Need",
        "authors": "Ashish Vaswani et al.",
        "total_copies": 4,
        "available_copies": 3,
        "availability": "Available",
        "is_reference": False,
        "shelf_location": "AIML-NLP-02",
        "page_number": 2,
        "topic": "Transformer architecture",
        "summary": "Self-attention Transformer that BERT uses as its encoder stack.",
    },
    {
        "query_key": "attention",
        "book_id": "vaswani2017_attention",
        "doc_id": "papers/Vaswani2017_Attention_Is_All_You_Need.pdf",
        "book_title": "Attention Is All You Need",
        "authors": "Ashish Vaswani et al.",
        "total_copies": 4,
        "available_copies": 3,
        "availability": "Available",
        "is_reference": False,
        "shelf_location": "AIML-NLP-02",
        "page_number": 3,
        "topic": "Scaled Dot-Product Attention",
        "summary": "Scaled dot-product attention: softmax(QK^T / sqrt(d_k)) V.",
    },
    {
        "query_key": "attention",
        "book_id": "devlin2018_bert",
        "doc_id": "papers/Devlin2018_BERT.pdf",
        "book_title": "BERT: Pre-training of Deep Bidirectional Transformers",
        "authors": "Jacob Devlin et al.",
        "total_copies": 5,
        "available_copies": 4,
        "availability": "Available",
        "is_reference": False,
        "shelf_location": "AIML-NLP-01",
        "page_number": 3,
        "topic": "Self-attention application",
        "summary": "Applies bidirectional self-attention in a deep Transformer encoder.",
    },
    {
        "query_key": "dbms_buffer",
        "book_id": "database_system_concepts_silberschatz",
        "doc_id": "",
        "book_title": "Database System Concepts",
        "authors": "Abraham Silberschatz, Henry F. Korth, S. Sudarshan",
        "total_copies": 4,
        "available_copies": 4,
        "availability": "Available in library",
        "is_reference": True,
        "shelf_location": "DBMS-01",
        "page_number": 1,
        "topic": "Buffer pools",
        "summary": "Reference textbook chapters on the buffer manager and replacement policy.",
    },
    {
        "query_key": "dbms_buffer",
        "book_id": "database_management_systems_ramakrishnan",
        "doc_id": "",
        "book_title": "Database Management Systems",
        "authors": "Raghu Ramakrishnan, Johannes Gehrke",
        "total_copies": 5,
        "available_copies": 5,
        "availability": "Available in library",
        "is_reference": True,
        "shelf_location": "DBMS-02",
        "page_number": 1,
        "topic": "Buffer pools",
        "summary": "Reference companion on buffer pool management.",
    },
    {
        "query_key": "ostep_paging",
        "book_id": "ostep_three_easy_pieces",
        "doc_id": "ostep_three_easy_pieces/08_Paging.pdf",
        "book_title": "Operating Systems: Three Easy Pieces (OSTEP)",
        "authors": "Remzi H. Arpaci-Dusseau, Andrea C. Arpaci-Dusseau",
        "total_copies": 7,
        "available_copies": 4,
        "availability": "Available",
        "is_reference": False,
        "shelf_location": "OS-01",
        "page_number": 1,
        "topic": "Paging",
        "summary": "Virtual memory paging: page tables, VPNs, PFNs, and address translation.",
    },
    {
        "query_key": "ostep_paging",
        "book_id": "operating_system_concepts_silberschatz",
        "doc_id": "ostep_three_easy_pieces/08_Paging.pdf",
        "book_title": "Operating System Concepts (The Dinosaur Book)",
        "authors": "Abraham Silberschatz, Peter B. Galvin, Greg Gagne",
        "total_copies": 4,
        "available_copies": 4,
        "availability": "Available in library",
        "is_reference": True,
        "shelf_location": "OS-02",
        "page_number": 1,
        "topic": "Segmentation vs paging",
        "summary": "Reference comparison of segmentation and paging (pilot uses OSTEP paging chapter).",
    },
    {
        "query_key": "graphrag",
        "book_id": "graphrag_ms",
        "doc_id": "papers/Edge2024_GraphRAG.pdf",
        "book_title": "From Local to Global: GraphRAG (library copy)",
        "authors": "Microsoft Research",
        "total_copies": 2,
        "available_copies": 1,
        "availability": "Available",
        "is_reference": False,
        "shelf_location": "AIML-RAG-03",
        "page_number": 2,
        "topic": "GraphRAG community summaries",
        "summary": "Builds a knowledge graph, detects communities, and summarizes for global queries.",
    },
    {
        "query_key": "graphrag",
        "book_id": "lewis2020_rag",
        "doc_id": "papers/Lewis2020_RAG.pdf",
        "book_title": "Retrieval-Augmented Generation for Knowledge-Intensive NLP",
        "authors": "Patrick Lewis et al.",
        "total_copies": 4,
        "available_copies": 3,
        "availability": "Available",
        "is_reference": False,
        "shelf_location": "AIML-RAG-01",
        "page_number": 3,
        "topic": "Classic RAG baseline",
        "summary": "Dense retrieval plus generation baseline that GraphRAG extends.",
    },
    {
        "query_key": "peft_rank",
        "book_id": "hu2021_lora",
        "doc_id": "papers/Hu2021_LoRA.pdf",
        "book_title": "LoRA: Low-Rank Adaptation of Large Language Models",
        "authors": "Edward J. Hu et al.",
        "total_copies": 3,
        "available_copies": 2,
        "availability": "Available",
        "is_reference": False,
        "shelf_location": "AIML-PEFT-01",
        "page_number": 4,
        "topic": "LoRA",
        "summary": "Top PEFT method: low-rank adapters with frozen base weights.",
    },
    {
        "query_key": "peft_rank",
        "book_id": "lewis2020_rag",
        "doc_id": "papers/Lewis2020_RAG.pdf",
        "book_title": "Retrieval-Augmented Generation for Knowledge-Intensive NLP",
        "authors": "Patrick Lewis et al.",
        "total_copies": 4,
        "available_copies": 3,
        "availability": "Available",
        "is_reference": False,
        "shelf_location": "AIML-RAG-01",
        "page_number": 1,
        "topic": "RAG",
        "summary": "Top RAG paper for the PEFT + retrieval ranking demo.",
    },
    {
        "query_key": "peft_rank",
        "book_id": "peft_survey",
        "doc_id": "papers/Hu2021_LoRA.pdf",
        "book_title": "Parameter-Efficient Fine-Tuning Survey (library copy)",
        "authors": "Library PEFT Collection",
        "total_copies": 2,
        "available_copies": 1,
        "availability": "Available",
        "is_reference": True,
        "shelf_location": "AIML-PEFT-REF",
        "page_number": 1,
        "topic": "PEFT survey",
        "summary": "Reference survey of PEFT methods.",
    },
    {
        "query_key": "multi_rag_dbms",
        "book_id": "lewis2020_rag",
        "doc_id": "papers/Lewis2020_RAG.pdf",
        "book_title": "Retrieval-Augmented Generation for Knowledge-Intensive NLP",
        "authors": "Patrick Lewis et al.",
        "total_copies": 4,
        "available_copies": 3,
        "availability": "Available",
        "is_reference": False,
        "shelf_location": "AIML-RAG-01",
        "page_number": 3,
        "topic": "RAG",
        "summary": "RAG half of the multi-topic RAG + DBMS demo.",
    },
    {
        "query_key": "multi_rag_dbms",
        "book_id": "database_system_concepts_silberschatz",
        "doc_id": "",
        "book_title": "Database System Concepts",
        "authors": "Abraham Silberschatz, Henry F. Korth, S. Sudarshan",
        "total_copies": 4,
        "available_copies": 4,
        "availability": "Available in library",
        "is_reference": True,
        "shelf_location": "DBMS-01",
        "page_number": 1,
        "topic": "Buffer manager",
        "summary": "DBMS half of the multi-topic demo — reference textbook.",
    },
    {
        "query_key": "lora_vs_bert",
        "book_id": "hu2021_lora",
        "doc_id": "papers/Hu2021_LoRA.pdf",
        "book_title": "LoRA: Low-Rank Adaptation of Large Language Models",
        "authors": "Edward J. Hu et al.",
        "total_copies": 3,
        "available_copies": 2,
        "availability": "Available",
        "is_reference": False,
        "shelf_location": "AIML-PEFT-01",
        "page_number": 4,
        "topic": "LoRA adapters",
        "summary": "Adapter-style PEFT side of the LoRA vs BERT comparison.",
    },
    {
        "query_key": "lora_vs_bert",
        "book_id": "devlin2018_bert",
        "doc_id": "papers/Devlin2018_BERT.pdf",
        "book_title": "BERT: Pre-training of Deep Bidirectional Transformers",
        "authors": "Jacob Devlin et al.",
        "total_copies": 5,
        "available_copies": 4,
        "availability": "Available",
        "is_reference": False,
        "shelf_location": "AIML-NLP-01",
        "page_number": 5,
        "topic": "Fine-tuning BERT",
        "summary": "Full fine-tune baseline side of the LoRA vs BERT comparison.",
    },
]
