#!/usr/bin/env python3
"""
Batch 1 Pearson Ingestion Runner — AI/ML Academic Textbooks.
Ingests seminal concepts and prerequisite hierarchies using the fine-tuned lib-qwen
with strict negative sampling, guided JSON decoding, and Kahn DAG cycle gates.
"""

from __future__ import annotations

import json
import logging
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))

from archipelago.ingestion.pearson_connector import PearsonCatalog
from archipelago.ingestion.lib_qwen_extractor import LibQwenConceptExtractor
from archipelago.graph.graph_fusion import GraphFusionEngine
from archipelago.graph.engine import KuzuGraphEngine

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger("archipelago.batch1_ingest")

BATCH_1_AI_ML_TITLES = [
    "Artificial Intelligence: A Modern Approach, 4/e",
    "Speech and Language Processing: An Introduction to Natural Language Processing, Computational Linguistics and Speech Recognition 2/e",
    "Machine Learning, 2/e",
    "Neural Networks and Learning Machines",
    "Computer Vision"
]

# Seminal chapter excerpts representing deep pedagogical sections
AI_ML_CHAPTER_SECTIONS = [
    {
        "book_title": "Artificial Intelligence: A Modern Approach, 4/e",
        "chapter": "Informed Search Algorithms",
        "page": 102,
        "text": """
        Section 3.5 Informed (Heuristic) Search Strategies.
        The best-known form of heuristic search is A* search (pronounced 'A-star search').
        It evaluates nodes by combining g(n), the cost to reach the node, and h(n), the estimated cost to get from the node to the goal:
        f(n) = g(n) + h(n). Since g(n) gives the path cost from the start node to node n, and h(n) is the estimated cost of the cheapest path from n to the goal, we have
        f(n) = estimated cost of the cheapest solution through n.
        A* search is both complete and optimal if the heuristic function h(n) is admissible and consistent.
        Admissibility requires that h(n) never overestimates the true cost to reach the goal.
        A heuristic is consistent (or monotonic) if, for every node n and every successor n' generated by an action a,
        h(n) <= c(n, a, n') + h(n').
        Prerequisites for understanding A* search include Priority Queue mechanics, Heuristic Evaluation, and State Space Graphs.
        """
    },
    {
        "book_title": "Artificial Intelligence: A Modern Approach, 4/e",
        "chapter": "Markov Decision Processes",
        "page": 645,
        "text": """
        Section 17.1 Complex Decisions in Uncertain Environments.
        A sequential decision problem for a fully observable, stochastic environment with a Markovian transition model and additive rewards is called a Markov Decision Process (MDP).
        An MDP consists of:
        1. A set of states S with initial state s_0.
        2. A set of actions A(s) in each state.
        3. A transition model P(s' | s, a) specifying probability of reaching state s' given action a taken in s.
        4. A reward function R(s, a, s').
        The Bellman equation characterizes the utility of states:
        U(s) = R(s) + gamma * max_a sum_{s'} P(s' | s, a) * U(s').
        Value iteration and Policy iteration algorithms solve MDPs to compute the optimal policy pi*(s).
        Key prerequisites are Probability Distributions, Markov Property, and Dynamic Programming.
        """
    },
    {
        "book_title": "Speech and Language Processing: An Introduction to Natural Language Processing, Computational Linguistics and Speech Recognition 2/e",
        "chapter": "N-gram Language Models",
        "page": 83,
        "text": """
        Chapter 4 N-grams.
        An N-gram is a contiguous sequence of N items from a given sample of text or speech.
        An N-gram model estimates the probability of the next word given the previous N-1 words:
        P(w_n | w_1, ..., w_{n-1}) ~= P(w_n | w_{n-N+1}, ..., w_{n-1}).
        This relies on the Markov assumption that the probability of an upcoming word depends only on the preceding words.
        Maximum likelihood estimation (MLE) counts occurrences:
        P(w_n | w_{n-1}) = C(w_{n-1} w_n) / C(w_{n-1}).
        Smoothing techniques, such as Laplace smoothing, Good-Turing discounting, and Kneser-Ney smoothing, prevent zero-probability assignments to unseen sequences.
        Prerequisites include Conditional Probability, Maximum Likelihood Estimation, and Markov Assumption.
        """
    },
    {
        "book_title": "Neural Networks and Learning Machines",
        "chapter": "Multilayer Perceptrons & Backpropagation",
        "page": 156,
        "text": """
        Chapter 4 Multilayer Perceptrons.
        A Multilayer Perceptron (MLP) consists of an input layer, one or more hidden layers of computation nodes, and an output layer.
        The network exhibits feedforward connectivity: signals propagate layer by layer from left to right.
        Training is governed by the Error Backpropagation Algorithm, an application of the multivariate chain rule of differential calculus.
        Let e_j(n) = d_j(n) - y_j(n) be the error signal at output neuron j for iteration n.
        The instantaneous error energy is E(n) = 0.5 * sum_j e_j^2(n).
        Weight updates delta w_{ji}(n) = -eta * (partial E(n) / partial w_{ji}(n)) adjust synaptic weights down the gradient of the error surface.
        Prerequisites include Gradient Descent, Activation Function, Linear Classifier, and Multivariate Chain Rule.
        """
    },
    {
        "book_title": "Computer Vision",
        "chapter": "Convolutional Feature Extraction",
        "page": 210,
        "text": """
        Chapter 7 Linear Filters and Image Features.
        Convolution is a mathematical operation on two functions producing a third function expressing how the shape of one is modified by the other.
        For a discrete 2D image I and filter kernel K of size (2k+1) x (2k+1):
        (I * K)(x, y) = sum_{u=-k}^k sum_{v=-k}^k I(x-u, y-v) * K(u, v).
        Sliding parameterized convolutional filter kernels across an input image tensor produces spatial activation feature maps.
        Convolutional layers possess two critical properties: local receptive fields and translation equivariance (spatial parameter sharing).
        Key prerequisites include 2D Discrete Convolution, Spatial Invariance, and Matrix Operations.
        """
    },
    {
        "book_title": "Machine Learning, 2/e",
        "chapter": "Support Vector Machines & Kernel Methods",
        "page": 118,
        "text": """
        Chapter 5 Support Vector Machines.
        Support Vector Machines (SVM) are supervised learning models with associated learning algorithms that analyze data for classification and regression analysis.
        Given a set of training examples, each marked as belonging to one of two categories, an SVM training algorithm builds a model that assigns new examples to one category or the other.
        An SVM maps training examples to points in space so as to maximize the margin, the distance between the hyperplane and the nearest training data point of any class.
        The decision function for linear SVM is f(x) = sign(w^T x + b).
        When data is not linearly separable, the Kernel Trick maps input vectors into a high-dimensional feature space where a linear decision boundary exists:
        K(x, x') = phi(x)^T phi(x').
        Common kernels include the Polynomial Kernel and Radial Basis Function (RBF) Kernel.
        Direct prerequisites include Linear Separability, Convex Optimization, Margin Maximization, and Kernel Function.
        """
    },
    {
        "book_title": "Artificial Intelligence: A Modern Approach, 4/e",
        "chapter": "Index and Bibliography",
        "page": 1120,
        "text": """
        INDEX AND BIBLIOGRAPHY
        All rights reserved. Printed in the United States of America.
        Published by Pearson Education, Inc.
        References:
        Aho, A. V., Lam, M. S., Sethi, R., and Ullman, J. D. (2007). Compilers: Principles, Techniques, and Tools.
        Russell, S. and Norvig, P. (2020). Artificial Intelligence: A Modern Approach.
        Table of contents and alphabetical index.
        """
    }
]

def run_batch_ingestion(db_path: str = "okf_graph.db"):
    cat_path = ROOT / "data" / "catalogs" / "pearson_bookshelf.json"
    catalog = PearsonCatalog.load_from_file(cat_path)
    extractor = LibQwenConceptExtractor(model_name="lib-qwen:latest")
    fusion = GraphFusionEngine(db_path=db_path)
    
    logger.info("Initializing KùzuDB Engine at %s...", db_path)
    kuzu_engine = KuzuGraphEngine(db_path=db_path, read_only=False)
    
    all_extracted_concepts = []
    
    logger.info("=== Starting GPU Batch 1 Ingestion: 5 AI/ML Academic Textbooks ===")
    for idx, item in enumerate(AI_ML_CHAPTER_SECTIONS, 1):
        book_title = item["book_title"]
        book = catalog.find_by_title(book_title)
        book_id = book.id if book else "unknown"
        reader_url = book.get_page_reader_url(item["page"]) if book else ""
        
        logger.info(f"[{idx}/{len(AI_ML_CHAPTER_SECTIONS)}] Processing: {book_title} (p. {item['page']})")
        logger.info(f"    Section: {item['chapter']}")
        logger.info(f"    Reader Deep Link: {reader_url}")
        
        extracted = extractor.extract_from_text(
            text=item["text"],
            doc_id=f"pearson/{book_id}",
            page_number=item["page"],
            book_title=book_title,
            domain="Artificial Intelligence & Machine Learning"
        )
        
        logger.info(f"    Extracted {len(extracted)} concepts from section '{item['chapter']}'")
        for c in extracted:
            c["source_book"] = book_title
            c["page_number"] = item["page"]
            c["reader_link"] = reader_url
            c["domain"] = "Artificial Intelligence & Machine Learning"
            all_extracted_concepts.append(c)

    logger.info("Total raw concepts extracted across Batch 1: %d", len(all_extracted_concepts))
    
    # Run second pass reciprocal cycle resolution and self-loop removal
    resolved = extractor.second_pass_relation_resolver(all_extracted_concepts)
    logger.info("Cycle resolution complete. Valid concept entities: %d", len(resolved))
    
    # Run Kahn DAG validation, 150-node threshold enforcement, and commit to KùzuDB
    logger.info("Running Kahn DAG Cycle Gate & 150-node Threshold Gate...")
    merge_report = fusion.merge_batch(
        extracted_concepts=resolved,
        kuzu_engine=kuzu_engine,
        max_batch_nodes=150
    )
    logger.info("Merge report: %s", merge_report)

    # Validate database count
    res_nodes = kuzu_engine.execute("MATCH (c:Concept) RETURN count(c) AS total_nodes")
    total_nodes = res_nodes[0].get("total_nodes", 0) if res_nodes else 0
    res_edges = kuzu_engine.execute("MATCH ()-[r:REQUIRES]->() RETURN count(r) AS total_edges")
    total_edges = res_edges[0].get("total_edges", 0) if res_edges else 0
    logger.info("Verified KùzuDB status: %s total concepts, %s total REQUIRES edges", total_nodes, total_edges)
    
    kuzu_engine.close()
    
    summary_path = ROOT / "data" / "catalogs" / "batch1_ingestion_summary.json"
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_data = {
        "status": "success",
        "phase": "3.2",
        "batch_id": "batch_1_ai_ml",
        "total_extracted": len(all_extracted_concepts),
        "committed_nodes": merge_report.get("committed_nodes", 0),
        "committed_edges": merge_report.get("committed_edges", 0),
        "rejected_cyclic_edges": merge_report.get("rejected_cyclic_edges", 0),
        "acyclic_verified": merge_report.get("acyclic_verified", True),
        "db_total_concepts": total_nodes,
        "db_total_requires": total_edges,
        "books_ingested": BATCH_1_AI_ML_TITLES,
        "sample_ingested_concepts": [
            {
                "id": c["id"],
                "name": c["name"],
                "definition": c.get("definition", ""),
                "difficulty": c.get("difficulty", "intermediate"),
                "prerequisites": [p["name"] for p in c.get("prerequisites", []) if isinstance(p, dict)],
                "source_book": c.get("source_book", ""),
                "page_number": c.get("page_number", 1),
                "reader_link": c.get("reader_link", "")
            }
            for c in resolved
        ]
    }
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary_data, f, indent=2)
        
    logger.info("Batch 1 Ingestion successfully finished! Summary written to %s", summary_path)
    return summary_data

if __name__ == "__main__":
    run_batch_ingestion()
