"""Auto-split from monolith — blocks are verbatim."""
from __future__ import annotations

from . import _deps as _rt  # noqa: F401


def evaluate_quiz_and_route_roadmap(
    quiz_responses: dict,
    target_concept_id: str,
    quiz_data: dict | None = None,
    max_hops: int = 6,
) -> dict:
    """Evaluate student's quiz responses, determine highest mastered prerequisite X, and return roadmap X -> Y.

    Args:
        quiz_responses: dict mapping question index or concept_id -> chosen option letter (e.g. {"1": "A", "2": "C"}).
        target_concept_id: The ultimate learning goal Y.
        quiz_data: The quiz generated by _rt.generate_diagnostic_quiz (generated fresh if None).
        max_hops: Maximum roadmap hops (1 to 6).
    """
    if not quiz_data:
        quiz_data = _rt.generate_diagnostic_quiz(target_concept_id, num_questions=5)

    questions = quiz_data.get("questions", [])
    if not questions:
        return {"error": "Could not generate questions for target concept", "target_id": target_concept_id}

    mastered = []
    gaps = []
    score = 0

    for q in questions:
        q_idx_str = str(q["q_index"])
        cid = q["concept_id"]
        correct = q["correct_option"].upper().strip()
        user_ans = (
            quiz_responses.get(q_idx_str)
            or quiz_responses.get(q["q_index"])
            or quiz_responses.get(cid)
            or ""
        ).upper().strip()

        is_correct = user_ans == correct
        item = {
            "q_index": q["q_index"],
            "concept_id": cid,
            "concept_name": q["concept_name"],
            "difficulty": q["difficulty"],
            "user_answer": user_ans,
            "correct_answer": correct,
            "is_correct": is_correct,
            "explanation": q.get("explanation") or "",
        }
        if is_correct:
            score += 1
            mastered.append(item)
        else:
            gaps.append(item)

    total = len(questions)
    accuracy = score / total if total else 0.0

    if mastered:
        start_concept_id = mastered[-1]["concept_id"]
        start_concept_name = mastered[-1]["concept_name"]
    else:
        start_concept_id = questions[0]["concept_id"]
        start_concept_name = questions[0]["concept_name"]

    roadmap = _rt.find_roadmap_between(start_concept_id, target_concept_id, max_hops=max_hops)

    return {
        "target_concept": quiz_data["target_concept"],
        "score": f"{score}/{total}",
        "score_pct": round(accuracy * 100, 1),
        "mastered_count": score,
        "gap_count": total - score,
        "mastered_concepts": [m["concept_name"] for m in mastered],
        "gap_concepts": [g["concept_name"] for g in gaps],
        "baseline_concept": {
            "id": start_concept_id,
            "name": start_concept_name,
        },
        "roadmap": roadmap,
        "details": {
            "mastered": mastered,
            "gaps": gaps,
        },
    }
