// Re-publish the public surface on window so inline onclick handlers and
// legacy classic scripts keep working, exactly like the old global script.
import { API_CONTRACT, API_HOST, AVATAR_HI_SRC, AVATAR_STORY, AVATAR_THINK_KEY, AVATAR_THINK_SRC, CHAT_RESPONSE_TIMEOUT_MS, CURRENT_ORIGIN, GRAPH_HOST, MAX_HISTORY_TURNS_SENT, STREAM_HARD_TIMEOUT_MS, STREAM_IDLE_TIMEOUT_MS, _avatarClipEls, _avatarIndexForKey, _graphPort, _onAvatarClipEnded, _pageHost, _pagePort, _showAvatarClipAt, buildAvatarClipsHtml, buildAvatarHtml, getStickyAvatar, hideStickyAvatar, pauseAvatarRoot, pauseAvatarVideo, playAvatarVideo, primeAvatarVideo, setAvatarThinking, setLibrarianThinking, showStickyAvatar, wireAvatarVideos } from './00-current-origin.js';
import { _glowWrap, _hideWelcomeWithTransition, _isGenDesc, _updateGlowState, escapeHTML, renderMarkdownSafely, sanitizeMarkdown } from './01--hide-welcome-with-transitio.js';
import { HF_CANONICAL_DOCS, HF_DATASET_BASE, _KW_HIGHLIGHTS, _enrichAssistantMarkup, appendEvidenceRail, citationPageUrl, copyPearsonCreds, getPearsonBookEntry, getResponseCitations, showPearsonCredentialToast } from './02--kw-highlights.js';
import { checkConnection, closeAllSidePanels, isPanelOpen, renderCurriculumPaths, setChatAvailability, setPanelOpen, syncPanelToggleUI, textarea, toggleLeftSidebar, togglePipeline, wrapLibraryInventorySection } from './03-wrap-library-inventory-secti.js';
import { CATALOG_55, DOM_SECTIONS, getCategory, getDocCollection, setupFilterButtons, startNewChat } from './04-start-new-chat.js';
import { displayBooks, renderBookStack, resolveLibraryReaderLink } from './05-display-books.js';
import { buildPagePdfUrl, closeReadingMode, highlightPassageText, openBookOrUnavailable, openReadingMode } from './06-open-book-or-unavailable.js';
import { autoPrompt, copyBibtex, handleKey, handleSendBtnClick, openPageViewerModal, promptFromConcept, setMode, setReadingView, setSendButtonState, stopGeneration } from './07-open-page-viewer-modal.js';
import { sendMessage } from './08-send-message.js';
import { PATTERNS, _addBubbleRipple, _addChatBubbleEffects, appendMessage, initThinkingOrbLoader } from './09-patterns.js';
import { DEFAULT_FEATURED_GRAPH, _nodeId, _nodeLabel, _nodeSummary, populatePipeline, selectGraphNode } from './10-populate-pipeline.js';
import { dismissGraphChoiceModal, getOrCreateInteractiveZone, populateTopology, showGraphChoiceModal, toggleGraphCardsSetting, toggleHorizontalGraphCard, updateGraphToggleUI } from './11-populate-topology.js';
import { chooseGraphExperience, openPrerequisiteRemediationReader, renderGraphExperiencePrompt, startPersonalizedQnA, switchToNormalGraph, switchToPersonalizedGraph } from './12-choose-graph-experience.js';
import { renderHorizontalGraphCard } from './13-render-horizontal-graph-card.js';
import { handleAdaptiveRadioChange, renderAdaptiveMCQCard } from './14-render-adaptive-mcqcard.js';
import { advanceAdaptiveStep, revealFinalCorrectQuestionAndFinish, submitAdaptiveAnswer } from './15-submit-adaptive-answer.js';
import { renderPersonalizedGraphCard } from './16-render-personalized-graph-ca.js';
import { drawPersonalizedSVG, selectPersonalizedNode } from './17-draw-personalized-svg.js';
import { _initGraphRipple, scrollInChatGraph, selectHorizontalNode } from './18--init-graph-ripple.js';
import { drawHorizontalSVG } from './19-draw-horizontal-svg.js';
import { _compactHistory, _writeSessions, clearAllSessions, closeRoadmapModal, deleteSession, flashShareBtn, loadSession, loadSharedChat, renderChatHistory, saveSession, shareChat } from './20--compact-history.js';
import { generateQuiz, generateRoadmap } from './21-generate-roadmap.js';

const api = {
  API_CONTRACT,
  API_HOST,
  AVATAR_HI_SRC,
  AVATAR_STORY,
  AVATAR_THINK_KEY,
  AVATAR_THINK_SRC,
  CATALOG_55,
  CHAT_RESPONSE_TIMEOUT_MS,
  CURRENT_ORIGIN,
  DEFAULT_FEATURED_GRAPH,
  DOM_SECTIONS,
  GRAPH_HOST,
  HF_CANONICAL_DOCS,
  HF_DATASET_BASE,
  MAX_HISTORY_TURNS_SENT,
  PATTERNS,
  STREAM_HARD_TIMEOUT_MS,
  STREAM_IDLE_TIMEOUT_MS,
  _KW_HIGHLIGHTS,
  _addBubbleRipple,
  _addChatBubbleEffects,
  _avatarClipEls,
  _avatarIndexForKey,
  _compactHistory,
  _enrichAssistantMarkup,
  _glowWrap,
  _graphPort,
  _hideWelcomeWithTransition,
  _initGraphRipple,
  _isGenDesc,
  _nodeId,
  _nodeLabel,
  _nodeSummary,
  _onAvatarClipEnded,
  _pageHost,
  _pagePort,
  _showAvatarClipAt,
  _updateGlowState,
  _writeSessions,
  advanceAdaptiveStep,
  appendEvidenceRail,
  appendMessage,
  autoPrompt,
  buildAvatarClipsHtml,
  buildAvatarHtml,
  buildPagePdfUrl,
  checkConnection,
  chooseGraphExperience,
  citationPageUrl,
  clearAllSessions,
  closeAllSidePanels,
  closeReadingMode,
  closeRoadmapModal,
  copyBibtex,
  copyPearsonCreds,
  deleteSession,
  dismissGraphChoiceModal,
  displayBooks,
  drawHorizontalSVG,
  drawPersonalizedSVG,
  escapeHTML,
  flashShareBtn,
  generateQuiz,
  generateRoadmap,
  getCategory,
  getDocCollection,
  getOrCreateInteractiveZone,
  getPearsonBookEntry,
  getResponseCitations,
  getStickyAvatar,
  handleAdaptiveRadioChange,
  handleKey,
  handleSendBtnClick,
  hideStickyAvatar,
  highlightPassageText,
  initThinkingOrbLoader,
  isPanelOpen,
  loadSession,
  loadSharedChat,
  openBookOrUnavailable,
  openPageViewerModal,
  openPrerequisiteRemediationReader,
  openReadingMode,
  pauseAvatarRoot,
  pauseAvatarVideo,
  playAvatarVideo,
  populatePipeline,
  populateTopology,
  primeAvatarVideo,
  promptFromConcept,
  renderAdaptiveMCQCard,
  renderBookStack,
  renderChatHistory,
  renderCurriculumPaths,
  renderGraphExperiencePrompt,
  renderHorizontalGraphCard,
  renderMarkdownSafely,
  renderPersonalizedGraphCard,
  resolveLibraryReaderLink,
  revealFinalCorrectQuestionAndFinish,
  sanitizeMarkdown,
  saveSession,
  scrollInChatGraph,
  selectGraphNode,
  selectHorizontalNode,
  selectPersonalizedNode,
  sendMessage,
  setAvatarThinking,
  setChatAvailability,
  setLibrarianThinking,
  setMode,
  setPanelOpen,
  setReadingView,
  setSendButtonState,
  setupFilterButtons,
  shareChat,
  showGraphChoiceModal,
  showPearsonCredentialToast,
  showStickyAvatar,
  startNewChat,
  startPersonalizedQnA,
  stopGeneration,
  submitAdaptiveAnswer,
  switchToNormalGraph,
  switchToPersonalizedGraph,
  syncPanelToggleUI,
  textarea,
  toggleGraphCardsSetting,
  toggleHorizontalGraphCard,
  toggleLeftSidebar,
  togglePipeline,
  updateGraphToggleUI,
  wireAvatarVideos,
  wrapLibraryInventorySection,
};
for (const [name, value] of Object.entries(api)) {
  window[name] = value;
}
